name: {{name.snakeCase()}}
description: "A new Fegno Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  #* State Management
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3

  #* Network call handling
  dio: ^5.3.3
  internet_connection_checker: ^1.0.0+1

  #* Data class generation
  freezed_annotation: ^2.4.1

  #* Network image diffrent state handling
  cached_network_image: ^3.3.1

  #* UI
  shimmer: ^3.0.0
  pinput: ^4.0.0
  sms_autofill: ^2.3.0
  percent_indicator: ^4.2.3

  #* Project deatails
  package_info_plus: ^5.0.1

  #* Linux
  dev_preview:
    git: https://github.com/salahu01/dev_preview.git

  #* Local storage
  shared_preferences: ^2.2.2

  #* Svg support
  flutter_svg: ^2.0.10+1

  #* Multiple Language Management
  flutter_localizations:
    sdk: flutter
  intl: any

  #* UI
  flutter_keyboard_visibility: ^6.0.0
  in_app_review: ^2.0.9

  #* Playes
  fc_native_video_thumbnail: ^0.8.0

  #* Pick files
  file_picker: ^6.2.0
  image_picker: ^1.0.7

  #* Medias
  record: ^5.0.4

  #* Managing Directories
  path_provider: ^2.1.2
  audioplayers: ^5.2.1

  #* Notfication
  awesome_notifications: ^0.9.2
  # awesome_notifications_core: ^0.9.1
  # awesome_notifications_fcm: ^0.9.2

  #*Firebase
  firebase_core: ^2.27.1
  # firebase_crashlytics: ^3.4.19
  firebase_messaging: ^14.7.20

  #*Permissions
  permission_handler: ^11.3.0

  #* Convertion
  encrypt: ^5.0.3

  #* Redirectional
  url_launcher: ^6.2.5

  #* App Updating [ Version Management ]
  in_app_update: ^4.2.2
  firebase_crashlytics: ^3.4.19
  firebase_analytics: ^10.8.10

dependency_overrides:
  web: any
  intl: any
  package_info_plus: any

dev_dependencies:
  #* code generation
  build_runner: ^2.4.8

  #* for freezed data class genearation
  freezed: ^2.4.6

  #* for analyse packages
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/svg/
    - assets/fonts/

  fonts:
    - family: Inter-Regular
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
    - family: Inter-Medium
      fonts:
        - asset: assets/fonts/Inter-Medium.ttf
    - family: Inter-Bold
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf
    - family: Inter-SemiBold
      fonts:
        - asset: assets/fonts/Inter-SemiBold.ttf
